# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'  
        goals: 'clean install'     
        options: '-DskipTests=false'  
        mavenOptions: '-Xmx1024m' 
        publishJUnitResults: true  
        testResultsFiles: '**/target/surefire-reports/*.xml' 

- stage: RegressionTests
  jobs:
  - job: RegressionJob
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'  
        goals: 'test'             
        options: ''
        mavenOptions: '-Xmx1024m'  
        publishJUnitResults: true   
        testResultsFiles: '**/target/surefire-reports/*.xml'  

- script: echo "Build and regression tests completed."
  displayName: 'Notify build and test completion'
